### ISSUE TITLE
Unhandled Exception: Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by fbazbo** [creomobile/combos#3]
If you set cleanAfterSelection true for TypeaheadCombo, you invariably get the subject exception. You don't have a default value for the closeAfterItemTapped:

```  @protected
  void itemTapped(TItem item, {@required bool closeAfterItemTapped}) {
    if (widget.onItemTapped != null) widget.onItemTapped(item);
    if (closeAfterItemTapped) super.close();
  }
```
but you end up calling it with just a null argument in initState method here:

```      clearSelected();
      if (widget.selected != null) super.itemTapped(null);
```
I even see the exception for a default value of cleanAfterSelection, if I select something and then start to delete characters from the end of the selection.

**Comment by fbazbo** [comment]
Here's the trace:
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Failed assertion: boolean expression must not be null
#0      ListComboState.itemTapped (package:combos/combos.dart:1861:9)
#1      SelectorComboState.itemTapped (package:combos/combos.dart:2043:11)
#2      TypeaheadComboState.initState.<anonymous closure> (package:combos/combos.dart:2334:42)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:207:21)
#4      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:274:5)
#5      EditableTextState._value= (package:flutter/src/widgets/editable_text.dart:1394:23)
#6      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:1680:5)
#7      EditableTextState.updateEditingValue (package:flutter/src/widgets/editable_text.dart:1261:5)
#8      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1067:36)
#9      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_cha<…>
